import SwiftUI
import Observation

@MainActor
@Observable
public class InspectionViewModel {
    public var checklist: InspectionChecklist
    public var isCompleted: Bool = false
    public var showingCamera: Bool = false
    public var expandedItemId: String?
    public var showingExportSheet: Bool = false

    public init(vehicleId: String = "VH-001", driverId: String = "DR-001", type: InspectionType = .preTrip) {
        self.checklist = InspectionChecklist(vehicleId: vehicleId, driverId: driverId, type: type)
    }

    // MARK: - Item Actions

    public func toggleItem(at index: Int) {
        guard checklist.items.indices.contains(index) else { return }
        checklist.items[index].passed.toggle()
    }

    public func updateNotes(at index: Int, notes: String) {
        guard checklist.items.indices.contains(index) else { return }
        checklist.items[index].notes = notes
    }

    public func setPhoto(at index: Int, data: Data?) {
        guard checklist.items.indices.contains(index) else { return }
        checklist.items[index].photoData = data
    }

    public func removePhoto(at index: Int) {
        guard checklist.items.indices.contains(index) else { return }
        checklist.items[index].photoData = nil
    }

    public func toggleExpanded(for itemId: String) {
        if expandedItemId == itemId {
            expandedItemId = nil
        } else {
            expandedItemId = itemId
        }
    }

    // MARK: - Completion

    public func completeInspection() {
        checklist.completedAt = Date()
        withAnimation(.spring(response: 0.5, dampingFraction: 0.8)) {
            isCompleted = true
        }
    }

    public var vehicleStatus: String {
        checklist.allPassed ? "Ready" : "Needs Attention"
    }

    // MARK: - PDF Report Generation

    public func generateReport() -> Data {
        let checklist = self.checklist
        var report = """
        ══════════════════════════════════════════════
                    FMS VEHICLE INSPECTION REPORT
        ══════════════════════════════════════════════

        Type:           \(checklist.inspectionType.rawValue) Inspection
        Vehicle ID:     \(checklist.vehicleId)
        Driver ID:      \(checklist.driverId)
        Date:           \(formattedDate(checklist.createdAt))
        Completed:      \(checklist.completedAt.map { formattedDate($0) } ?? "In Progress")
        Status:         \(vehicleStatus)
        Progress:       \(checklist.completedCount) / \(checklist.totalCount) items passed

        ──────────────────────────────────────────────
        INSPECTION ITEMS
        ──────────────────────────────────────────────

        """

        for item in checklist.items {
            let status = item.passed ? "✅ PASS" : "❌ FAIL"
            report += """
            \(item.category.rawValue): \(status)
            """
            if !item.notes.isEmpty {
                report += """

                Notes: \(item.notes)
                """
            }
            if item.photoData != nil {
                report += """

                📷 Photo attached
                """
            }
            report += "\n\n"
        }

        if !checklist.overallNotes.isEmpty {
            report += """
            ──────────────────────────────────────────────
            OVERALL NOTES
            ──────────────────────────────────────────────
            \(checklist.overallNotes)

            """
        }

        let failedItems = checklist.failedItems
        if !failedItems.isEmpty {
            report += """
            ──────────────────────────────────────────────
            ⚠️  ITEMS REQUIRING ATTENTION
            ──────────────────────────────────────────────

            """
            for item in failedItems {
                report += "  • \(item.category.rawValue)"
                if !item.notes.isEmpty {
                    report += " — \(item.notes)"
                }
                report += "\n"
            }
        }

        report += """

        ══════════════════════════════════════════════
        Generated by FMS • \(formattedDate(Date()))
        ══════════════════════════════════════════════
        """

        return Data(report.utf8)
    }

    private func formattedDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd MMM yyyy, HH:mm"
        return formatter.string(from: date)
    }
}
